"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-01 16:50:03.405986
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "path_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app", sa.String(length=16), nullable=False),
        sa.Column("from_prefix", sa.Text(), nullable=False),
        sa.Column("to_prefix", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("categories_json", sa.Text(), nullable=False),
        sa.Column("extra_word_ids_json", sa.Text(), nullable=False),
        sa.Column("pad_pre_ms", sa.Integer(), nullable=False),
        sa.Column("pad_post_ms", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("handled", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_events", schema=None) as batch_op:
        batch_op.create_index("ix_webhook_events_received_at", ["received_at"], unique=False)

    op.create_table(
        "whitelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=True),
        sa.Column("canonical_word", sa.Text(), nullable=False),
        sa.Column("context_text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("whitelist", schema=None) as batch_op:
        batch_op.create_index("ix_whitelist_scope", ["scope", "scope_id"], unique=False)

    op.create_table(
        "word_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("forms_json", sa.Text(), nullable=False),
        sa.Column("is_phrase", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical", name="uq_word_entries_canonical"),
    )
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("arr_path", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "arr_id", name="uq_titles_kind_arr_id"),
    )
    op.create_table(
        "media_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("arr_file_id", sa.Integer(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("episode_title", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_job_id", sa.String(length=36), nullable=True),
        sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title_id", "season", "episode", name="uq_media_items_title_s_e"),
    )
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.create_index("ix_media_items_path", ["path"], unique=False)
        batch_op.create_index("ix_media_items_status", ["status"], unique=False)

    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("media_item_id", sa.Integer(), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("backup_path", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("sha1_prefix", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.create_index("ix_backups_media_item_id", ["media_item_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=True),
        sa.Column("progress_pct", sa.Float(), nullable=False),
        sa.Column("claimed_by", sa.String(length=64), nullable=True),
        sa.Column("heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("work_dir", sa.Text(), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("stt_mode", sa.String(length=16), nullable=True),
        sa.Column("model_used", sa.String(length=64), nullable=True),
        sa.Column("subtitle_source", sa.Text(), nullable=True),
        sa.Column("profile_snapshot_json", sa.Text(), nullable=True),
        sa.Column("timings_json", sa.Text(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_claim", ["state", "priority", "created_at"], unique=False)
        batch_op.create_index("ix_jobs_media_item_id", ["media_item_id"], unique=False)

    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.Integer(), nullable=False),
        sa.Column("word_raw", sa.Text(), nullable=False),
        sa.Column("word_canonical", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("mute_start_s", sa.Float(), nullable=False),
        sa.Column("mute_end_s", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("muted", sa.Boolean(), nullable=False),
        sa.Column("whitelisted", sa.Boolean(), nullable=False),
        sa.Column("suspicious", sa.Boolean(), nullable=False),
        sa.Column("subtitle_cue_idx", sa.Integer(), nullable=True),
        sa.Column("snippet_path", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.create_index("ix_detections_job_word", ["job_id", "word_canonical"], unique=False)
        batch_op.create_index("ix_detections_media_item_id", ["media_item_id"], unique=False)

    op.create_table(
        "job_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("msg", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.create_index("ix_job_logs_job_id_ts", ["job_id", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_logs_job_id_ts")

    op.drop_table("job_logs")
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.drop_index("ix_detections_media_item_id")
        batch_op.drop_index("ix_detections_job_word")

    op.drop_table("detections")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_media_item_id")
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.drop_index("ix_backups_media_item_id")

    op.drop_table("backups")
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.drop_index("ix_media_items_status")
        batch_op.drop_index("ix_media_items_path")

    op.drop_table("media_items")
    op.drop_table("titles")
    op.drop_table("word_entries")
    with op.batch_alter_table("whitelist", schema=None) as batch_op:
        batch_op.drop_index("ix_whitelist_scope")

    op.drop_table("whitelist")
    with op.batch_alter_table("webhook_events", schema=None) as batch_op:
        batch_op.drop_index("ix_webhook_events_received_at")

    op.drop_table("webhook_events")
    op.drop_table("settings")
    op.drop_table("profiles")
    op.drop_table("path_mappings")
    # ### end Alembic commands ###
